version: 1.0.{build}
image: Visual Studio 2019

configuration: Release

install:
  - ps: Install-Product node $env:NODE_VERSION
  - npm install

build: off

build_script:
  - npm run build

test_script:
  - npm run lint && npm test

artifacts:
  - path: '**/coverage/lcov-report/index.html'
    name: Coverage Report
